/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.dataagent.semantic.service;

import io.agentscope.dataagent.semantic.converter.SemanticToOntologyCatalogAdapter;
import io.agentscope.dataagent.semantic.model.SemanticCube;
import io.agentscope.dataagent.semantic.model.SemanticModel;
import io.agentscope.dataagent.semantic.model.SemanticModelTable;
import io.agentscope.dataagent.semantic.model.SemanticRelationship;
import io.agentscope.dataagent.semantic.parser.SemanticModelParser;
import io.agentscope.dataagent.semantic.parser.SemanticModelValidator;
import io.agentscope.dataagent.web.persistence.jpa.SemanticModelEntity;
import io.agentscope.dataagent.web.persistence.jpa.SemanticModelRepository;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * 语义模型核心服务：上传/自动生成/存储/图谱数据转换/schema 描述生成。
 *
 * <p>语义模型来源决策（互斥）：
 * <ul>
 *   <li>用户上传 ontology.json → 直接解析存储，不再生成</li>
 *   <li>用户未上传 → 从表结构自动建模</li>
 * </ul>
 */
@Service
public class SemanticModelService {

    private static final Logger log = LoggerFactory.getLogger(SemanticModelService.class);

    /** 语义上下文输出阈值（字符数），超过则截断。 */
    private static final int SCHEMA_DESCRIBE_THRESHOLD = 30_000;

    private final SemanticModelRepository repository;
    private final SemanticModelParser parser;
    private final SemanticModelValidator validator;

    public SemanticModelService(
            SemanticModelRepository repository,
            SemanticModelParser parser,
            SemanticModelValidator validator) {
        this.repository = repository;
        this.parser = parser;
        this.validator = validator;
    }

    // ---- CRUD ----

    /**
     * 上传 ontology.json：解析 → 校验 → 计算 hash → 持久化。
     *
     * @param ownerId 用户 ID
     * @param groupId 数据集分组 ID
     * @param jsonText ontology.json 原始文本
     * @return 持久化实体
     */
    @Transactional
    public SemanticModelEntity uploadModel(String ownerId, String groupId, String jsonText) {
        SemanticModel model = parser.parse(jsonText);

        // 校验
        List<String> errors = validator.validate(model);
        if (!errors.isEmpty()) {
            throw new IllegalArgumentException("语义模型校验失败: " + String.join("; ", errors));
        }

        // 计算 MDL hash
        String mdlHash = computeHash(jsonText);

        // UPSERT：同 group 只保留一份
        Optional<SemanticModelEntity> existing =
                repository.findByOwnerIdAndGroupId(ownerId, groupId);
        SemanticModelEntity entity =
                existing.orElseGet(
                        () -> {
                            SemanticModelEntity e = new SemanticModelEntity();
                            e.setId(UUID.randomUUID().toString());
                            e.setOwnerId(ownerId);
                            e.setGroupId(groupId);
                            return e;
                        });

        entity.setName(model.getDescription() != null ? model.getDescription() : "语义模型");
        entity.setDescription(model.getDescription());
        entity.setMdlJson(parser.toJson(model));
        entity.setMdlHash(mdlHash);
        entity.setOrigin("uploaded");
        entity.setUpdatedAt(Instant.now());
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(Instant.now());
        }

        repository.save(entity);
        log.info(
                "SemanticModelService: 上传语义模型 (owner={}, group={}, hash={})",
                ownerId,
                groupId,
                mdlHash);
        return entity;
    }

    /**
     * 保存自动生成的语义模型（不覆盖用户上传的）。
     */
    @Transactional
    public SemanticModelEntity saveAutoGenerated(
            String ownerId, String groupId, SemanticModel model) {
        // 如果已有用户上传的，不覆盖
        if (hasUploadedModel(ownerId, groupId)) {
            log.info(
                    "SemanticModelService: 已有用户上传模型，跳过自动生成 (owner={}, group={})", ownerId, groupId);
            return repository.findByOwnerIdAndGroupId(ownerId, groupId).orElse(null);
        }

        String jsonText = parser.toJson(model);
        String mdlHash = computeHash(jsonText);

        Optional<SemanticModelEntity> existing =
                repository.findByOwnerIdAndGroupId(ownerId, groupId);
        SemanticModelEntity entity =
                existing.orElseGet(
                        () -> {
                            SemanticModelEntity e = new SemanticModelEntity();
                            e.setId(UUID.randomUUID().toString());
                            e.setOwnerId(ownerId);
                            e.setGroupId(groupId);
                            return e;
                        });

        entity.setName(model.getDescription() != null ? model.getDescription() : "自动生成语义模型");
        entity.setDescription(model.getDescription());
        entity.setMdlJson(jsonText);
        entity.setMdlHash(mdlHash);
        entity.setOrigin("auto-generated");
        entity.setUpdatedAt(Instant.now());
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(Instant.now());
        }

        repository.save(entity);
        log.info("SemanticModelService: 自动生成语义模型 (owner={}, group={})", ownerId, groupId);
        return entity;
    }

    /**
     * 获取指定 group 的语义模型。
     */
    public Optional<SemanticModel> getModel(String ownerId, String groupId) {
        return repository
                .findByOwnerIdAndGroupId(ownerId, groupId)
                .map(e -> parser.fromJson(e.getMdlJson()));
    }

    /**
     * 获取指定 group 的语义模型（仅通过 groupId，不校验 owner）。
     */
    public Optional<SemanticModel> getModelByGroupId(String groupId) {
        List<SemanticModelEntity> entities = repository.findByGroupId(groupId);
        if (entities.isEmpty()) {
            return Optional.empty();
        }
        // 优先返回用户上传的
        return entities.stream()
                .filter(e -> "uploaded".equals(e.getOrigin()))
                .findFirst()
                .or(() -> entities.stream().findFirst())
                .map(e -> parser.fromJson(e.getMdlJson()));
    }

    /** 是否有用户上传的模型。 */
    public boolean hasUploadedModel(String ownerId, String groupId) {
        return repository
                .findByOwnerIdAndGroupId(ownerId, groupId)
                .map(e -> "uploaded".equals(e.getOrigin()))
                .orElse(false);
    }

    @Transactional
    public void delete(String ownerId, String modelId) {
        repository
                .findById(modelId)
                .filter(e -> e.getOwnerId().equals(ownerId))
                .ifPresent(
                        e -> {
                            String instructions = e.getInstructionsText();
                            if (instructions != null && !instructions.isBlank()) {
                                // 保留业务文档：软清除模型内容，instructions 不丢
                                e.setMdlJson("{}");
                                e.setMdlHash("");
                                e.setOrigin("cleared");
                                e.setUpdatedAt(Instant.now());
                                repository.save(e);
                            } else {
                                repository.delete(e);
                            }
                        });
    }

    // ---- Instructions（业务规则 + 数据限制）----

    /**
     * 保存 instructions.md 内容（业务规则 + 数据限制）。
     * 如果同 group 已有语义模型，则附加到该模型；否则创建空模型壳并存储 instructions。
     */
    @Transactional
    public void saveInstructions(String ownerId, String groupId, String instructionsText) {
        Optional<SemanticModelEntity> existing =
                repository.findByOwnerIdAndGroupId(ownerId, groupId);
        SemanticModelEntity entity =
                existing.orElseGet(
                        () -> {
                            SemanticModelEntity e = new SemanticModelEntity();
                            e.setId(java.util.UUID.randomUUID().toString());
                            e.setOwnerId(ownerId);
                            e.setGroupId(groupId);
                            e.setName("语义模型");
                            e.setOrigin("uploaded");
                            e.setMdlJson("{}");
                            e.setMdlHash("");
                            return e;
                        });
        entity.setInstructionsText(instructionsText);
        entity.setUpdatedAt(Instant.now());
        repository.save(entity);
        log.info(
                "SemanticModelService: 保存 instructions (owner={}, group={}, length={})",
                ownerId,
                groupId,
                instructionsText != null ? instructionsText.length() : 0);
    }

    /**
     * 获取指定 group 的 instructions 文本。
     */
    public String getInstructionsText(String ownerId, String groupId) {
        return repository
                .findByOwnerIdAndGroupId(ownerId, groupId)
                .map(SemanticModelEntity::getInstructionsText)
                .orElse(null);
    }

    public String getInstructionsText(String groupId) {
        List<SemanticModelEntity> entities = repository.findByGroupId(groupId);
        return entities.stream()
                .filter(e -> e.getInstructionsText() != null && !e.getInstructionsText().isBlank())
                .findFirst()
                .map(SemanticModelEntity::getInstructionsText)
                .orElse(null);
    }

    /**
     * 生成完整的语义上下文（schema 描述 + instructions），供 LLM 工具调用。
     * 小模型返回全文（≤ 30K 字符），大模型截断并提示。
     */
    public String describeSchemaWithInstructions(String groupId) {
        Optional<SemanticModel> opt = getModelByGroupId(groupId);
        if (opt.isEmpty()) {
            String instructions = getInstructionsText(groupId);
            return instructions != null ? instructions : "当前知识库未配置语义模型。";
        }

        StringBuilder sb = new StringBuilder();
        sb.append(describeSchema(opt.get()));

        String instructions = getInstructionsText(groupId);
        if (instructions != null && !instructions.isBlank()) {
            sb.append("\n\n").append(instructions);
        }

        String result = sb.toString();
        // 混合策略：超过阈值时截断并提示
        if (result.length() > SCHEMA_DESCRIBE_THRESHOLD) {
            log.warn("语义上下文超过阈值 ({}>{}), 截断输出", result.length(), SCHEMA_DESCRIBE_THRESHOLD);
            return result.substring(0, SCHEMA_DESCRIBE_THRESHOLD)
                    + "\n\n[上下文已截断，请缩小查询范围或使用 recall_similar_queries 获取参考]";
        }
        return result;
    }

    // ---- 图谱数据 ----

    /**
     * 获取前端图谱数据（nodes + edges），供 SemanticGraphView 渲染。
     */
    public Map<String, Object> getGraphData(String ownerId, String groupId) {
        Optional<SemanticModelEntity> entity = repository.findByOwnerIdAndGroupId(ownerId, groupId);
        if (entity.isEmpty()) {
            return Map.of("nodes", List.of(), "edges", List.of());
        }
        SemanticModel model = parser.fromJson(entity.get().getMdlJson());
        Map<String, Object> out = new LinkedHashMap<>(buildGraphData(model));
        out.put("meta", buildMeta(entity.get(), model));
        return out;
    }

    /**
     * 图谱元信息：来源/更新时间/各类计数 + 规则/局限/instructions 原文，
     * 供知识图谱 tab 的来源 badge 与右侧规则面板展示。
     */
    private Map<String, Object> buildMeta(SemanticModelEntity entity, SemanticModel model) {
        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("modelId", entity.getId());
        meta.put("origin", entity.getOrigin());
        meta.put(
                "updatedAt",
                entity.getUpdatedAt() == null ? null : entity.getUpdatedAt().toString());
        meta.put("modelCount", model.getModels() != null ? model.getModels().size() : 0);
        meta.put(
                "relationshipCount",
                model.getRelationships() != null ? model.getRelationships().size() : 0);
        meta.put("cubeCount", model.getCubes() != null ? model.getCubes().size() : 0);
        meta.put("ruleCount", model.getRules() != null ? model.getRules().size() : 0);
        meta.put(
                "limitationCount",
                model.getLimitations() != null ? model.getLimitations().size() : 0);
        String instructions = entity.getInstructionsText();
        meta.put("hasInstructions", instructions != null && !instructions.isBlank());
        meta.put("rules", model.getRules() != null ? model.getRules() : List.of());
        meta.put(
                "limitations", model.getLimitations() != null ? model.getLimitations() : List.of());
        meta.put("instructionsText", instructions);
        return meta;
    }

    /**
     * 获取本体目录形状数据（objects/relationships/metrics/rules/limitations），
     * 供对象目录等视图以 legacy 本体契约消费语义模型；无模型或仅空壳时返回空。
     */
    public Optional<Map<String, Object>> getCatalogData(String ownerId, String groupId) {
        return repository
                .findByOwnerIdAndGroupId(ownerId, groupId)
                .map(e -> parser.fromJson(e.getMdlJson()))
                .filter(m -> m.getModels() != null && !m.getModels().isEmpty())
                .map(SemanticToOntologyCatalogAdapter::adapt);
    }

    /**
     * 将 SemanticModel 转换为前端 G6 图谱渲染所需的 nodes + edges 结构。
     */
    private Map<String, Object> buildGraphData(SemanticModel model) {
        List<Map<String, Object>> nodes = new ArrayList<>();
        List<Map<String, Object>> edges = new ArrayList<>();

        // Layer 1: Model 节点
        if (model.getModels() != null) {
            for (SemanticModelTable table : model.getModels()) {
                Map<String, Object> node = new LinkedHashMap<>();
                node.put("id", table.getName());
                node.put("type", "model");
                node.put("label", table.getLabel() != null ? table.getLabel() : table.getName());
                node.put("tableName", table.getTableName());
                node.put("kind", table.getKind());
                node.put("description", table.getDescription());
                node.put("columns", table.getColumns() != null ? table.getColumns() : List.of());
                nodes.add(node);
            }
        }

        // Layer 2: Relationship 边
        if (model.getRelationships() != null) {
            for (SemanticRelationship rel : model.getRelationships()) {
                Map<String, Object> edge = new LinkedHashMap<>();
                edge.put("id", rel.getName());
                edge.put("type", "relationship");
                edge.put("label", rel.getLabel() != null ? rel.getLabel() : rel.getName());
                edge.put("joinType", rel.getJoinType());
                edge.put("condition", rel.getCondition());
                if (rel.getModels() != null && rel.getModels().size() == 2) {
                    edge.put("source", rel.getModels().get(0));
                    edge.put("target", rel.getModels().get(1));
                }
                edges.add(edge);
            }
        }

        // Layer 3: Cube 节点 + cube-base 边
        if (model.getCubes() != null) {
            for (SemanticCube cube : model.getCubes()) {
                Map<String, Object> node = new LinkedHashMap<>();
                node.put("id", cube.getName());
                node.put("type", "cube");
                node.put("label", cube.getLabel() != null ? cube.getLabel() : cube.getName());
                node.put("baseObject", cube.getBaseObject());
                node.put("description", cube.getDescription());
                node.put("measures", cube.getMeasures() != null ? cube.getMeasures() : List.of());
                node.put(
                        "dimensions",
                        cube.getDimensions() != null ? cube.getDimensions() : List.of());
                node.put(
                        "timeDimensions",
                        cube.getTimeDimensions() != null ? cube.getTimeDimensions() : List.of());
                nodes.add(node);

                // cube → baseObject 边
                Map<String, Object> cubeEdge = new LinkedHashMap<>();
                cubeEdge.put("id", "cube-" + cube.getName());
                cubeEdge.put("source", cube.getName());
                cubeEdge.put("target", cube.getBaseObject());
                cubeEdge.put("type", "cube-base");
                cubeEdge.put("label", "baseObject");
                edges.add(cubeEdge);
            }
        }

        return Map.of("nodes", nodes, "edges", edges);
    }

    // ---- Schema 描述生成（注入 LLM 上下文）----

    /**
     * 生成语义模型的 schema 描述文本，注入到 LLM 系统提示词中。
     * 参考 WrenAI 的 describe_schema() 方法。
     */
    public String describeSchema(SemanticModel model) {
        StringBuilder sb = new StringBuilder();

        sb.append("# 语义模型\n\n");
        if (model.getDescription() != null) {
            sb.append(model.getDescription()).append("\n\n");
        }

        // Models
        if (model.getModels() != null && !model.getModels().isEmpty()) {
            sb.append("## 逻辑表\n\n");
            for (SemanticModelTable table : model.getModels()) {
                sb.append("### ").append(table.getName());
                if (table.getLabel() != null) {
                    sb.append(" (").append(table.getLabel()).append(")");
                }
                sb.append("\n");
                sb.append("- 物理表: ").append(table.getTableName()).append("\n");
                sb.append("- 类型: ").append(table.getKind()).append("\n");
                if (table.getDescription() != null) {
                    sb.append("- 说明: ").append(table.getDescription()).append("\n");
                }
                if (table.getColumns() != null && !table.getColumns().isEmpty()) {
                    sb.append("- 列:\n");
                    for (var col : table.getColumns()) {
                        sb.append("  - ")
                                .append(col.getName())
                                .append(" (")
                                .append(col.getType())
                                .append(")");
                        if (col.getLabel() != null) {
                            sb.append(" — ").append(col.getLabel());
                        }
                        if (col.getDescription() != null) {
                            sb.append(" [").append(col.getDescription()).append("]");
                        }
                        sb.append("\n");
                    }
                }
                sb.append("\n");
            }
        }

        // Relationships
        if (model.getRelationships() != null && !model.getRelationships().isEmpty()) {
            sb.append("## 关系（JOIN 条件）\n\n");
            for (SemanticRelationship rel : model.getRelationships()) {
                sb.append("- **").append(rel.getName()).append("**: ");
                if (rel.getModels() != null && rel.getModels().size() == 2) {
                    sb.append(rel.getModels().get(0)).append(" ↔ ").append(rel.getModels().get(1));
                }
                sb.append(" (").append(rel.getJoinType()).append(")\n");
                sb.append("  条件: `").append(rel.getCondition()).append("`\n");
            }
            sb.append("\n");
        }

        // Cubes
        if (model.getCubes() != null && !model.getCubes().isEmpty()) {
            sb.append("## Cube 预聚合指标\n\n");
            for (SemanticCube cube : model.getCubes()) {
                sb.append("### ").append(cube.getName());
                if (cube.getLabel() != null) {
                    sb.append(" (").append(cube.getLabel()).append(")");
                }
                sb.append("\n");
                if (cube.getDescription() != null) {
                    sb.append("- 说明: ").append(cube.getDescription()).append("\n");
                }
                sb.append("- 基础模型: ").append(cube.getBaseObject()).append("\n");
                if (cube.getMeasures() != null && !cube.getMeasures().isEmpty()) {
                    sb.append("- 度量:\n");
                    for (var m : cube.getMeasures()) {
                        sb.append("  - ")
                                .append(m.getName())
                                .append(": `")
                                .append(m.getExpression())
                                .append("`");
                        if (m.getDescription() != null) {
                            sb.append(" — ").append(m.getDescription());
                        }
                        sb.append("\n");
                    }
                }
                if (cube.getDimensions() != null && !cube.getDimensions().isEmpty()) {
                    sb.append("- 维度: ");
                    sb.append(
                            cube.getDimensions().stream()
                                    .map(d -> d.getName())
                                    .reduce((a, b) -> a + ", " + b)
                                    .orElse(""));
                    sb.append("\n");
                }
                if (cube.getTimeDimensions() != null && !cube.getTimeDimensions().isEmpty()) {
                    sb.append("- 时间维度: ");
                    sb.append(
                            cube.getTimeDimensions().stream()
                                    .map(d -> d.getName())
                                    .reduce((a, b) -> a + ", " + b)
                                    .orElse(""));
                    sb.append("\n");
                }
                sb.append("\n");
            }
        }

        // Rules
        if (model.getRules() != null && !model.getRules().isEmpty()) {
            sb.append("## 业务规则\n\n");
            for (var rule : model.getRules()) {
                sb.append("- **")
                        .append(rule.getId() != null ? rule.getId() : rule.getName())
                        .append("**: ")
                        .append(rule.getDescription())
                        .append("\n");
                if (rule.getSqlHint() != null) {
                    sb.append("  SQL提示: `").append(rule.getSqlHint()).append("`\n");
                }
            }
            sb.append("\n");
        }

        // Limitations
        if (model.getLimitations() != null && !model.getLimitations().isEmpty()) {
            sb.append("## 数据局限\n\n");
            for (var lim : model.getLimitations()) {
                sb.append("- **")
                        .append(lim.getId() != null ? lim.getId() : lim.getName())
                        .append("**: ")
                        .append(lim.getDescription())
                        .append("\n");
            }
        }

        return sb.toString();
    }

    // ---- 工具方法 ----

    /** 计算 SHA256 前16位作为 MDL hash。 */
    private String computeHash(String text) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(text.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 8 && i < digest.length; i++) {
                sb.append(String.format("%02x", digest[i]));
            }
            return sb.toString();
        } catch (Exception e) {
            log.warn("SHA-256 hash 计算失败", e);
            return UUID.randomUUID().toString().substring(0, 16);
        }
    }
}
